export const projectsWeb = [
  {
    title: 'Gitarologia',
    description: "This is a startup project. Gitarologia is a platform that will provide comprehensive guitar courses to anyone who wants to learn. The approach is on a new proven metodology od teaching popular guitar.",
      image: '/images/project-gitarologia.png',
      tags: ['Next.js', 'Mongo'],
    visit: 'https://gitarologia-34fg3qdnw-makragic.vercel.app/',
    id: 0,
  },
  {
    title: 'Plus50x',
    description: "The final project for Hardvard's CS50 - Introduction to Computer Science course. This is a redesign of Hardvard's learning platform, design with the idea of making all courses and materials easy to access.",
    image: '/images/project-plus50x.png',
    tags: ['Flask', 'SQLite'],
    source: 'https://github.com/vpopovic003/plus50x',
    video: 'https://www.youtube.com/watch?v=tWOz693ZLHE',
    id: 3,
  },
  {
    title: 'Restaurant Page',
    description: "A page for restaurant or fast food businesses.",
      image: '/images/project-restaurant.png',
      tags: ['ReactJS'],
    source: 'https://github.com/vpopovic003/restaurant-page/',
    visit: 'https://vpopovic003.github.io/restaurant-page/',
    id: 9,
  },  
  {
    title: 'Face-Brain',
    description:"An app that detect faces in photos using Clarifai API.",
    image: '/images/project-face-brain.png',
    tags: ['ReactJS'],
    source: 'https://github.com/vpopovic003/face-brain',
    visit: 'https://vpopovic003.github.io/face-brain/',
    id: 9,
  },
  {
    title: 'Robofriends',
    description:"This is a learning project for course 'The Complete Web Developer: Zero to Mastery.' This application generates random robot images fetched from JSON data using API, and allow a user to search through them.",
    image: '/images/project-robofriends.png',
    tags: ['ReactJS'],
    source: 'https://github.com/vpopovic003/robofriends',
    visit: 'https://vpopovic003.github.io/robofriends/',
    id: 1,
  },
  {
      title: 'Anitrone',
      description: "Windows software developed for client needs. This application can animate various elements in the metronome time, and then export the animation as mp4 file. Made in Python and Python's version of a QT library for making UI-s.",
      image: '/images/project-anitrone.png',
      tags: ['Python', 'PyQT'],
      source: 'https://github.com/vpopovic003/anitrone-python',
      download: 'https://drive.google.com/file/d/176ayloh-4kPHM3DLrq2thMoiO5AASAY9/view',
      id: 4,
  },
  {
    title: 'AnitroneWEB',
    description: "This served as a DEMO and a proof of concept for the later developed Anitrone Windows desktop application. This application can animate various elements in the metronome time.",
      image: '/images/project-anitroneweb.png',
      tags: ['HTML', 'CSS', 'JavaScript'],
    source: 'https://github.com/vpopovic003/anitrone-web',
    visit: 'https://vpopovic003.github.io/anitrone-web/',
    id: 5,
  },
  {
    title: 'Chordbox',
    description: "This is a web app made for client needs, and is used making guitar chord diagrams. You can select fingers and then export the image in PNG format.",
      image: '/images/project-chordbox.png',
      tags: ['HTML', 'CSS', 'JavaScript'],
    source: 'https://github.com/vpopovic003/chordbox',
    visit: 'https://vpopovic003.github.io/chordbox/',
    id: 6,
  },
  {
    title: 'CodeKeen',
    description: "This is a website made with 90s aesthetics, but using modern HTML5 and CSS3 aproach. It is a fun project that I made in spare time, as I am a fan of retro website aethetics.",
      image: '/images/project-codekeen.png',
      tags: ['HTML', 'CSS', 'JavaScript'],
    source: 'https://github.com/vpopovic003/codekeen',
    visit: 'https://vpopovic003.github.io/codekeen/',
    id: 7,
  },
  {
    title: 'Metronome',
    description: "A functional online metronome made using Next.js and Web Audio Api.",
      image: '/images/project-metronome.png',
      tags: ['Next.js'],
    visit: 'https://gitarologia-751hoil1h-makragic.vercel.app/',
    id: 8,
  },
];

export const TimeLineData = [
  { year: 2017, text: 'Started my journey', },
  { year: 2018, text: 'Worked as a freelance developer', },
  { year: 2019, text: 'Founded JavaScript Mastery', },
  { year: 2020, text: 'Shared my projects with the world', },
  { year: 2021, text: 'Started my own platform', },
];