export const projectsWeb = [
  {
    title: 'Gitarologia',
    description: "Web School full stack application. Startup. Demo page available.",
      image: '/images/project-gitarologia.png',
      tags: ['Next.js', 'Mongo'],
    visit: 'https://gitarologia-34fg3qdnw-makragic.vercel.app/',
    id: 0,
  },
  {
    title: 'Plus50x',
    description: "Full stack application. Web School for Harvard's CS50 course.",
    image: '/images/project-plus50x.png',
    tags: ['Flask', 'SQLite'],
    source: 'https://github.com/vpopovic003/plus50x',
    video: 'https://www.youtube.com/watch?v=tWOz693ZLHE',
    visit: 'https://plus50x.onrender.com',
    id: 3,
  },
  {
    title: 'Face-Brain',
    description:"Full stack application. Detects faces in photos using Clarifai API and stores users and entries in a database.",
    image: '/images/project-face-brain.png',
    tags: ['ReactJS', 'Express', 'PostgreSQL'],
    source: 'https://github.com/vpopovic003/face-brain',
    visit: 'https://face-brain-8dja.onrender.com/',
    id: 9,
  },
  {
    title: 'Restaurant Page',
    description: "A front page for restaurants or fast food businesses.",
      image: '/images/project-restaurant.png',
      tags: ['ReactJS'],
    source: 'https://github.com/vpopovic003/restaurant-page/',
    visit: 'https://vpopovic003.github.io/restaurant-page/',
    id: 9,
  },  
  
  {
    title: 'Robofriends',
    description:"This application generates random robot images fetched from API.",
    image: '/images/project-robofriends.png',
    tags: ['ReactJS'],
    source: 'https://github.com/vpopovic003/robofriends',
    visit: 'https://vpopovic003.github.io/robofriends/',
    id: 1,
  },
  {
      title: 'Anitrone',
      description: "Windows application that animates various elements and exports the animation in mp4 format.",
      image: '/images/project-anitrone.png',
      tags: ['Python', 'PyQT'],
      source: 'https://github.com/vpopovic003/anitrone-python',
      download: 'https://drive.google.com/file/d/176ayloh-4kPHM3DLrq2thMoiO5AASAY9/view',
      id: 4,
  },
  {
    title: 'AnitroneWEB',
    description: "Demo for Anitrone Windows app. Click on elements to change their shape, and press play for animation.",
      image: '/images/project-anitroneweb.png',
      tags: ['HTML', 'CSS', 'JavaScript'],
    source: 'https://github.com/vpopovic003/anitrone-web',
    visit: 'https://vpopovic003.github.io/anitrone-web/',
    id: 5,
  },
  {
    title: 'Chordbox',
    description: "A small web app that creates guitar chord tabs, and exports them as PNG.",
      image: '/images/project-chordbox.png',
      tags: ['HTML', 'CSS', 'JavaScript'],
    source: 'https://github.com/vpopovic003/chordbox',
    visit: 'https://vpopovic003.github.io/chordbox/',
    id: 6,
  },
  {
    title: 'CodeKeen',
    description: "Website with 90s aesthetics. A fun project.",
      image: '/images/project-codekeen.png',
      tags: ['HTML', 'CSS', 'JavaScript'],
    source: 'https://github.com/vpopovic003/codekeen',
    visit: 'https://vpopovic003.github.io/codekeen/',
    id: 7,
  },
  {
    title: 'Metronome',
    description: "A functional online metronome made using Next.js and Web Audio Api.",
      image: '/images/project-metronome.png',
      tags: ['Next.js'],
    visit: 'https://gitarologia-751hoil1h-makragic.vercel.app/',
    id: 8,
  },
];

export const TimeLineData = [
  { year: 2017, text: 'Started my journey', },
  { year: 2018, text: 'Worked as a freelance developer', },
  { year: 2019, text: 'Founded JavaScript Mastery', },
  { year: 2020, text: 'Shared my projects with the world', },
  { year: 2021, text: 'Started my own platform', },
];